[package]
name = "oxic-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "2.0.82", features = ["full"] }
quote = "1.0.37"

[lib]
proc-macro = true
